appName: emailservice
appImage: gcr.io/google-samples/microservices-demo/emailservice
appVersion: v0.8.0
appReplicas: 2
containerPort: 8080
containerEnvVar:
  - name: PORT
    value: "8080"


serviceType: nodePort 
servicePort: 5000