appName: productcatalogservice
appImage: gcr.io/google-samples/microservices-demo/productcatalogservice
appVersion: v0.8.0
appReplicas: 2
containerPort: 3550
containerEnvVar:
  - name: PORT
    value: "3550"
  - name: DISABLE_PROFILER
    value: "1"


serviceType: nodePort 
servicePort: 3550